name: kitchen_counter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  side_navigation: ^1.0.4
  flutter:
    sdk: flutter
  get: ^4.1.4  # Replace with the latest version of GetX
  http: ^1.1.0
  flutter_secure_storage: ^8.0.0
  
  english_words: ^4.0.0
  provider: ^6.0.0
  
  google_fonts: ^4.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  pie_chart: ^5.3.2
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

flutter:
  uses-material-design: true
  assets:
    - assets/
    - secrets.json
fonts:
  - family: Roboto
    fonts:
      - asset: Fonts/Roboto-Regular.ttf
